
using UnityEngine;
public class CSharp_G
{
    public static void RegisterAll()
    {
        if (JSMgr.allCallbackInfo.Count != 0)
        {
            Debug.LogError(999777454);
        }
         
        System_Runtime_Serialization_ISerializable_G.__Register();
        UnityEngine_RaycastHit2D_G.__Register();
        UnityEngine_UI_ICanvasElement_G.__Register();
        UnityEngine_UI_ILayoutController_G.__Register();
        UnityEngine_UI_IMaskable_G.__Register();
        UnityEngine_Collision2D_G.__Register();
        System_Runtime_Serialization_IDeserializationCallback_G.__Register();
        UnityEngine_EventSystems_IEventSystemHandler_G.__Register();
        UnityEngine_LayerMask_G.__Register();
        System_Collections_IDictionary_G.__Register();
        UnityEngine_Physics2D_G.__Register();
        UnityEngine_Screen_G.__Register();
        UnityEngine_Quaternion_G.__Register();
        UnityEngine_Physics_G.__Register();
        UnityEngine_Color_G.__Register();
        UnityEngine_Rect_G.__Register();
        UnityEngine_Mathf_G.__Register();
        UnityEngine_YieldInstruction_G.__Register();
        UnityEngine_UI_ILayoutElement_G.__Register();
        UnityEngine_NavMeshPath_G.__Register();
        UnityEngine_RaycastHit_G.__Register();
        UnityEngine_AnimatorStateInfo_G.__Register();
        UnityEngine_Resources_G.__Register();
        jsb_Test_Framwork_TestGeneric7__7_G.__Register();
        UnityEngine_Vector2_G.__Register();
        UnityEngine_Vector3_G.__Register();
        UnityEngine_Debug_G.__Register();
        UnityEngine_Input_G.__Register();
        UnityEngine_ISerializationCallbackReceiver_G.__Register();
        UnityEngine_Object_G.__Register();
        UnityEngine_WWW_G.__Register();
        UnityEngine_Time_G.__Register();
        UnityEngine_Application_G.__Register();
        jsb_Test_Framwork_TestRF_G.__Register();
        jsb_Test_Framwork_TestMisc_G.__Register();
        jsb_Test_Framwork_TestPerformance_G.__Register();
        UnityEngine_EventSystems_ISelectHandler_G.__Register();
        UnityEngine_EventSystems_IMoveHandler_G.__Register();
        UnityEngine_EventSystems_IDeselectHandler_G.__Register();
        UnityEngine_EventSystems_IPointerEnterHandler_G.__Register();
        UnityEngine_EventSystems_IPointerExitHandler_G.__Register();
        UnityEngine_EventSystems_IPointerClickHandler_G.__Register();
        UnityEngine_EventSystems_ISubmitHandler_G.__Register();
        UnityEngine_EventSystems_IPointerUpHandler_G.__Register();
        UnityEngine_Events_UnityEventBase_G.__Register();
        UnityEngine_UI_ILayoutGroup_G.__Register();
        UnityEngine_EventSystems_IPointerDownHandler_G.__Register();
        UnityEngine_Material_G.__Register();
        UnityEngine_Component_G.__Register();
        UnityEngine_AudioClip_G.__Register();
        UnityEngine_TextAsset_G.__Register();
        UnityEngine_WaitForSeconds_G.__Register();
        UnityEngine_GameObject_G.__Register();
        System_Collections_Hashtable_G.__Register();
        UnityEngine_Sprite_G.__Register();
        UnityEngine_Behaviour_G.__Register();
        UnityEngine_Rigidbody_G.__Register();
        UnityEngine_Renderer_G.__Register();
        UnityEngine_ParticleSystem_G.__Register();
        UnityEngine_Rigidbody2D_G.__Register();
        UnityEngine_Events_UnityEvent_G.__Register();
        UnityEngine_Collider_G.__Register();
        UnityEngine_Transform_G.__Register();
        UnityEngine_LineRenderer_G.__Register();
        UnityEngine_Collider2D_G.__Register();
        UnityEngine_SphereCollider_G.__Register();
        UnityEngine_Light_G.__Register();
        UnityEngine_AudioSource_G.__Register();
        UnityEngine_NavMeshAgent_G.__Register();
        UnityEngine_GUIElement_G.__Register();
        UnityEngine_ParticleSystemRenderer_G.__Register();
        UnityEngine_MeshCollider_G.__Register();
        UnityEngine_Camera_G.__Register();
        UnityEngine_SpriteRenderer_G.__Register();
        UnityEngine_Animator_G.__Register();
        UnityEngine_BoxCollider_G.__Register();
        UnityEngine_CapsuleCollider_G.__Register();
        UnityEngine_MonoBehaviour_G.__Register();
        UnityEngine_MeshRenderer_G.__Register();
        UnityEngine_UI_Button_ButtonClickedEvent_G.__Register();
        UnityEngine_Animation_G.__Register();
        UnityEngine_RectTransform_G.__Register();
        TestCallJs_G.__Register();
        UnityEngine_EventSystems_UIBehaviour_G.__Register();
        UnityEngine_BoxCollider2D_G.__Register();
        UnityEngine_CircleCollider2D_G.__Register();
        UnityEngine_PolygonCollider2D_G.__Register();
        UnityEngine_GUITexture_G.__Register();
        UnityEngine_GUIText_G.__Register();
        UnityEngine_UI_Selectable_G.__Register();
        UnityEngine_UI_LayoutGroup_G.__Register();
        UnityEngine_UI_Graphic_G.__Register();
        UnityEngine_UI_GridLayoutGroup_G.__Register();
        UnityEngine_UI_Button_G.__Register();
        UnityEngine_UI_MaskableGraphic_G.__Register();
        UnityEngine_UI_Text_G.__Register();
    }
}